name: Schedule test on Testing Farm
on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: "Test All (release)"
        uses: sclorg/testing-farm-as-github-action@v3
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          api_url: https://api.dev.testing-farm.io/v0.1
          compose: Fedora-41
          tmt_plan_regex: "test-all-release"
          pull_request_status_name: "Test All (release)"
          update_pull_request_status: "true"
          create_issue_comment: "true"
