name: envoy-openssl-checks
on:
  issue_comment:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write

jobs:
  build-and-test-release:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: build-and-test-release
        id: build-and-test-release
        uses: sclorg/testing-farm-as-github-action@v3
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          api_url: https://api.dev.testing-farm.io/v0.1
          compose: Fedora-41
          tmt_plan_regex: "build-and-test-release"
          pull_request_status_name: "build-and-test-release"
          update_pull_request_status: true
